/**
 * Test example of gracht protocol message version 2
 * Includes example of a test protocol and some test structures
 */

namespace test

struct transaction {
    uint32_t test_id;
}

struct transfer_status {
    uint32_t test_id;
    int      code;
}

service utils (0x1) {
    func print(string text) : (int result) = 1;
    func transfer(transaction transaction) : (transfer_status result) = 2;
    func transfer_many(transaction[] transactions) : (transfer_status[] results) = 3;
    func get_event(int count) : () = 4;

    event myevent : (int n) = 5;
    event transfer_status : transfer_status = 6;
}
