/**
 * Test example of gracht protocol message version 2
 * Includes example of a test protocol and some test structures
 */

namespace test

struct transaction {
    uint32  test_id;
    string  serial;
    uint8[] data;
}

struct transfer_status {
    uint32 test_id;
    int    code;
}

service utils (0x1) {
    func print(string text) : (int result) = 1;
    func transfer(transaction transaction) : (transfer_status result) = 2;
    func transfer_many(transaction[] transactions) : (transfer_status[] results) = 3;
    func transfer_data(uint8[] data) : () = 4;
    func receive_data() : (uint8[] data) = 5;
    func get_event(int count) : () = 6;
    func shutdown() : () = 7;

    event myevent : (int n) = 8;
    event transfer_status : transfer_status = 9;
}
