/**
 * Test example of gracht protocol message version 2
 * Includes example of a test protocol and some test structures
 */

import "test_structs"
namespace gracht

// define calculator service with id of 1
service calculator (0x1) {
    func add(int a, int b) : (int result) = 1;
    func add_many(int[] inputs) : (int result) = 2;
    func print(string text) : (int result) = 3;

    func getHistory() : (string history) = 4;
    func getHistories() : (string[] histories) = 5;

    func getVehicle() : (vehicle result) = 6;
    func setVehicle(vehicle vehicle) : () = 7;

    func transfer(transfer_request request) : (int status) = 8;
    func transfer_many(transfer_request[] request) : (int[] statuses) = 9;

    event error : (int code, string description) = 10;
    event transfer_complete : transfer_complete_event = 11;
}

service control (2) {
    func subscribe(uint8_t protocol) : () = 1;
    func unsubscribe(uint8_t protocol) : () = 2;

    event error : (uint32_t messageId, int errorCode) = 3;
}
