/**
 * Test example of gracht protocol message version 2
 * Includes example of a test protocol and some test structures
 */

import "test_structs"
namespace gracht

// define calculator service with id of 1
service calculator (0x1) {
    func add(int a, int b) : (int result);
    func add_many(int[] inputs) : (int result);
    func print(string text) : (int result);

    func getHistory() : (string history);
    func getHistories() : (string[] histories);

    func transfer(transfer_request request) : (int status);
    func transfer_many(transfer_request[] request) : (int[] statuses);

    event error : (int code, string description);
    event transfer_complete : transfer_complete_event;
}

service control (2) {
    func subscribe(uint8_t protocol) : ();
    func unsubscribe(uint8_t protocol) : ();

    event error : (uint32_t messageId, int errorCode);
}
